apiVersion: 1

deleteDatasources:
  - name: 'Prometheus'
    orgId: 1

datasources:
  - name: 'Prometheus'
    type: 'prometheus'
    access: 'proxy'
    orgId: 1
    url: 'http://192.168.240.4:9090'
    isDefault: true
    version: 1
    editable: false